projectName: eyal-test
environment: dev

awsRegion: us-east-1

applications:
  - name: main
    type: server
    serviceType: NodePort
    route: 
      enabled: true
      host: dev.testserver.apps.cluster.carmel6000.org
      path: /
    image: 160569206162.dkr.ecr.us-east-1.amazonaws.com/heroes-live-on
    imageTag: 8ae38ed9743003d909bdd9b8a5d84fe140daee67
    replicas: 2
    containerPort: 8080
    configs: 
       PORT: "8080"
       CONFIG_ENV: staging
       NODE_ENV: production
    secrets: 
      - name:  global-config
        path: heroes-live-on/config-global
      - name:  env-config
        path: heroes-live-on/config
      - name: rds-config 
        path: heroes-live-on/config-rds
  - name: main-client
    type: client
    route: 
      enabled: true
      host: client.testserver.apps.cluster.carmel6000.org
      path: /
    image: 160569206162.dkr.ecr.us-east-1.amazonaws.com/helo-main-client
    imageTag: v3
    replicas: 1
    containerPort: 3000
