apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: heroes-live-on
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: 'https://github.com/hilma-tech/argo.git'
      revision: main
      files:
        - path: 'apps/heroes-live-on/**/values.yaml'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      sources:
        - repoURL: 'https://hilma-tech.github.io/helm-charts/'
          targetRevision: 0.1.6
          chart: generic-app
          helm:
            valueFiles:
              - '$values/{{path}}/values.yaml' 
        - repoURL: 'https://github.com/hilma-tech/argo.git'
          targetRevision: main
          ref: values
          
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'heroes-live-on-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
